---
# prometheus_alertmanager/tasks/main.yml

- name: 'Populate the package name variable depending on the OS'
  ansible.builtin.include_tasks: package_name.yml

- name: 'Populate the service name variable depending on the OS'
  ansible.builtin.include_tasks: service_name.yml

- name: 'Install the package'
  ansible.builtin.package:
    name: "{{ prometheus_alertmanager_package_name }}"
    state: 'present'

- name: 'Create the configuration file'
  ansible.builtin.template:
    src: 'alertmanager.yml.j2'
    dest: '/etc/prometheus/alertmanager.yml'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'Restart the Alertmanager service'

- name: 'Start and enable the service'
  ansible.builtin.service:
    name: "{{ prometheus_alertmanager_service_name }}"
    state: 'started'
    enabled: 'true'
